### ISSUE TITLE
Testing all Images from Test Folder

### ISSUE THREAD

**Issue by redhat12345** [AAnoosheh/ComboGAN#4]
Hi,

I have 1000 images in each test folders. I need to generate images from all the test images. I have 3 domains. So, I need to generate 1000 * 3 = 3000 images from one test folders. 
Please let me know how can I do that?

**Comment by AAnoosheh** [comment]
Hello, you can turn on the testing flag `--serial_test` and set `--how_many 3000`
By default testing only selects a random 50 images for quick evaluation, so this ensures it goes through every image once in sequential order.

**Comment by redhat12345** [comment]
Thank you so much for your reply. Actually, I have a different number of images in each test folders. for an example, I have 1200 images in one domain, 1509 in other domain, and 1900 is other domain test folders. It would be great if we are capable to test every image once in sequential order. 

I run this command, but itill I did not get all test images.
 
python test.py --phase test  --dataroot ./datasets/data  --name data  --n_domains 3  --which_epoch 90  --show_matrix --serial_test

**Comment by AAnoosheh** [comment]
Well, now that changes things a bit  :)

So I have a commit on my personal dev branch that lets me do exactly what you need, so let me push that now.

EDIT: Pushed. Update your repo and try now.

I updated the behavior of `--serial_test` so now it automatically goes through all your test folders once, and the `--how_many` argument is ignored if `--serial_test` is active.

Also, I would highly recommend removing the `--show_matrix` flag since it will produce a bunch of visualization images that you probably don't need.

**Comment by redhat12345** [comment]
@AAnoosheh thank you so much for your kind reply.
